spring:
  application:
    name: recommendation-service

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8082